import network
import ubinascii

# Pins and hardware config
SELECT_PIN = 12
CANCEL_PIN = 9
ROTA_PIN = 10
ROTB_PIN = 11
I2C_SCL_PIN = 15
I2C_SDA_PIN = 14
ADC_PIN = 26
OLED_HEIGHT = 64
OLED_WIDTH = 128

# Events
SELECT_EVENT = 1
CANCEL_EVENT = 2
ROTARY_CW_EVENT = 3
ROTARY_CCW_EVENT = 4
MOVE_ON_EVENT = 5

# Screens
STARTUP_SCREEN = 1
HOME_SCREEN = 2
MEASURE_SCREEN = 3
ANALYSIS_SCREEN = 4
HISTORY_SCREEN = 5
PATIENTS_SCREEN = 6
MEASUREMENT_SCREEN = 7

# Measure
NEEDED_SAMPLES = 10
TIME_OFFSET = 3 * 3600
MIN_PPI = 500
MAX_PPI = 1200
THRESHOLD_DIVIDER = 1.6

# Network
DEVICE_NAME = "Picolai2"
SSID = "KMD652_Group_1"
PASSWORD = "salasana1Miro"
BROKER_IP = "192.168.1.253"
BROKER_PORT = 21883
